theratrove/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;
using System.Xml;
using theratrove.data;
using theratrove.Helper;
using theratrove.Models;

namespace theratrove.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        private int pageSize = 10;
        private TheratroveDB db = new TheratroveDB();
        private int maxLocationValue;

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Therapist(int? Id)
        {
            var result = db.Therapists.Where(t => t.Id == Id && t.Active == true).FirstOrDefault();
            var ratingList = result.TherapistRatings.ToList();
            ViewBag.TherapistRating = Math.Round(ratingList.Average(e => e.Rating).GetValueOrDefault(0), 2);
            ViewBag.TherapistCount = ratingList.Count();

            return View(result);
        }

        public ActionResult Condition(string Name, int pageNo = 1)
        {
            var searchResults = new theratrove.Models.SearchResults();

            this.FillSearchFilters(searchResults);

            searchResults.TherapistList = (from pd in db.Therapists
                                           join od in db.TherapistTypesOfTherapies on pd.Id equals od.TherapistID
                                           where od.TherapyType.Value == Name && pd.Active == true
                                           orderby pd.FirstName
                                           select pd).ToList();

            searchResults.CurrentPage = pageNo;

            if (searchResults.TherapistList != null && searchResults.TherapistList.Count > 0)
            {
                searchResults.NoOfRecords = searchResults.TherapistList.Count;

                if (pageNo == 1 && searchResults.TherapistList.Count > (pageNo * pageSize))
                {
                    searchResults.RecordsRange = string.Format("{0}-{1} of {2}", 1, (pageNo * pageSize), searchResults.NoOfRecords);
                }
                else if ((pageNo * pageSize) >= searchResults.NoOfRecords)
                {
                    if (pageNo == 1)
                    {
                        searchResults.RecordsRange = string.Format("{0} of {1}", searchResults.NoOfRecords, searchResults.NoOfRecords);
                    }
                    else
                    {
                        searchResults.RecordsRange = string.Format("{0} of {1}", ((pageNo - 1) * (pageSize)), searchResults.NoOfRecords);
                    }
                }
                else
                {
                    searchResults.RecordsRange = string.Format("{0}-{1} of {2}", ((pageNo - 1) * pageSize), (pageNo * pageSize), searchResults.NoOfRecords);
                }

                searchResults.TherapistList = searchResults.TherapistList.Skip((pageNo - 1) * pageSize)
                // Take only what is being asked for.
                .Take(pageSize)
                // NOW pull it from the database.
                .ToList();
                this.SetRatting(searchResults);
                this.LogSearchFilters(searchResults, "", "", Name);
                return View("Therapistlist", searchResults);
            }
            else
            {
                return View("Therapistlist");
            }
        }

        public ActionResult Location(string Name, int pageNo = 1)
        {
            var searchResults = new theratrove.Models.SearchResults();

            this.FillSearchFilters(searchResults);
            searchResults.location = Name;
            searchResults.TherapistList = db.Therapists.Where(th => th.City.Equals(Name) && th.Active == true).OrderBy(f => f.FirstName).ToList();
            searchResults.CurrentPage = pageNo;

            if (searchResults.TherapistList != null && searchResults.TherapistList.Count > 0)
            {
                searchResults.NoOfRecords = searchResults.TherapistList.Count;
                if (pageNo == 1 && searchResults.TherapistList.Count > (pageNo * pageSize))
                {
                    searchResults.RecordsRange = string.Format("{0}-{1} of {2}", 1, (pageNo * pageSize), searchResults.NoOfRecords);
                }
                else if ((pageNo * pageSize) >= searchResults.NoOfRecords)
                {
                    if (pageNo == 1)
                    {
                        searchResults.RecordsRange = string.Format("{0} of {1}", searchResults.NoOfRecords, searchResults.NoOfRecords);
                    }
                    else
                    {
                        searchResults.RecordsRange = string.Format("{0} of {1}", ((pageNo - 1) * (pageSize)), searchResults.NoOfRecords);
                    }
                }
                else
                {
                    searchResults.RecordsRange = string.Format("{0}-{1} of {2}", ((pageNo - 1) * pageSize), (pageNo * pageSize), searchResults.NoOfRecords);
                }

                searchResults.TherapistList = searchResults.TherapistList.Skip((pageNo - 1) * pageSize)
                // Take only what is being asked for.
                .Take(pageSize)
                // NOW pull it from the database.
                .ToList();
                this.SetRatting(searchResults);
                this.LogSearchFilters(searchResults, Name, "");
                searchResults.ActivePage = pageNo;
                return View("Therapistlist", searchResults);
            }
            else
            {
                return View("Therapistlist");
            }
        }

        public ActionResult Therapistlist(int pageNo = 1)
        {
            SearchResults searchResults = new SearchResults();

            this.FillSearchFilters(searchResults);

            searchResults.TherapistList = db.Therapists.Where(e => e.Active == true).OrderBy(f => f.FirstName).ToList();
            searchResults.CurrentPage = pageNo;

            if (searchResults.TherapistList != null && searchResults.TherapistList.Count > 0)
            {
                searchResults.NoOfRecords = searchResults.TherapistList.Count;
                if (pageNo == 1 && searchResults.TherapistList.Count > (pageNo * pageSize))
                {
                    searchResults.RecordsRange = string.Format("{0}-{1} of {2}", 1, (pageNo * pageSize), searchResults.TherapistList.Count);
                }
                else if (((pageNo + 1) * pageSize) >= searchResults.TherapistList.Count || (pageNo * pageSize) <= searchResults.TherapistList.Count)
                {
                    searchResults.RecordsRange = string.Format("{0} of {1}", searchResults.TherapistList.Count, searchResults.TherapistList.Count);
                }
                else
                {
                    searchResults.RecordsRange = string.Format("{0}-{1} of {2}", ((pageNo - 1) * pageSize), (pageNo * pageSize), searchResults.TherapistList.Count);
                }

                searchResults.TherapistList = searchResults.TherapistList.Skip((pageNo - 1) * pageSize)
                // Take only what is being asked for.
                .Take(pageSize)
                // NOW pull it from the database.
                .ToList();
                this.SetRatting(searchResults);
            }

            //return PartialView("_TherapistList", searchResults);
            ViewBag.FilterPara = null;
            searchResults.ActivePage = pageNo;
            return View("Therapistlist", searchResults);
            //return View("TherapistlistTest", searchResults);
        }

        [HttpPost]
        public ActionResult FilterTherapist(SearchResults searchResults, string keyworksearch, string location, int pageNo = 1)
        {
            TempData.Clear();
            TempData.Add("searchResults", searchResults);
            TempData.Add("keyworksearch", keyworksearch);
            TempData.Add("location", location);
            TempData.Add("pageNo", pageNo);

            this.FillSearchFilters(searchResults);
            searchResults.location = location;
            searchResults.keyword = keyworksearch;
            this.SearchTherapist(searchResults, keyworksearch, location, pageNo);
            searchResults.ActivePage = pageNo;
            this.SetRatting(searchResults);
            this.LogSearchFilters(searchResults, location, keyworksearch);
            return View("Therapistlist", searchResults);
            //return PartialView("_TherapistList", searchResults);
        }

        //[HttpGet]
        //public ActionResult FilterTherapist()
        //{
        //    object searchResults;
        //    string keyworksearch, location;
        //    int pageNo;
        //    if (TempData.ContainsKey("searchResults"))
        //    {
        //        searchResults = TempData["searchResults"];
        //    }
        //    if (TempData.ContainsKey("keyworksearch"))
        //    {
        //        keyworksearch = Convert.ToString(TempData["keyworksearch"]);
        //    }
        //    if (TempData.ContainsKey("location"))
        //    {
        //        location = Convert.ToString(TempData["location"]);
        //    }
        //    if (TempData.ContainsKey("pageNo"))
        //    {
        //        pageNo = Convert.ToInt32(TempData["pageNo"]);
        //    }

        //    //return RedirectToAction("Therapistlist", { searchResults, keyworksearch,location,pageNo });
        //}

        private void FillSearchFilters(SearchResults searchResults)
        {
            //if (ApplicationCashManager.filterOptions == null)
            //{
            //    List<FiltersDetail> obj = new List<FiltersDetail>();
            //    var fiters = db.SearchFilters.ToList();
            //    foreach (var item in fiters.OrderBy(d => d.DisplayOrderNo).ToList())
            //    {
            //        var filterdetail = new FiltersDetail
            //        {

theratrove/Views/Search/Faith.cshtml
 <div class="job_title">For</div>
                    <div class="borderfull-width"></div>
                    <div class="page-heading">
                        <div class="category">
                            <div class="col-md-1 p-l p-r">
                                <input type="checkbox" id="PHP" name="ossm">
                            </div>
                            <div class="col-md-11 p-l p-r">
                                <label for="PHP">PHP</label>
                            </div>
                        </div>
                        <div class="category">
                            <div class="col-md-1 p-l p-r">
                                <input type="checkbox" id="HTML" name="ossm" checked="">
                            </div>
                            <div class="col-md-11 p-l p-r">
                                <label for="HTML">HTML</label>
                            </div>
                        </div>
                        <div class="category">
                            <div class="col-md-1 p-l p-r">
                                <input type="checkbox" id="CSS" name="ossm">
                            </div>
                            <div class="col-md-11 p-l p-r">
                                <label for="CSS">CSS</label>
                            </div>
                        </div>
                        <div class="category">
                            <div class="col-md-1 p-l p-r">
                                <input type="checkbox" id="JavaScript" name="ossm">
                            </div>
                            <div class="col-md-11 p-l p-r">
                                <label for="JavaScript">JavaScript</label>
                            </div>
                        </div>
                        <div class="category">
                            <div class="col-md-1 p-l p-r">
                                <input type="checkbox" id="jQueary" name="ossm">
                            </div>
                            <div class="col-md-11 p-l p-r">
                                <label for="jQueary">jQueary</label>
                            </div>
                        </div>
                        <div class="category">
                            <div class="col-md-1 p-l p-r">
                                <input type="checkbox" id="MySQL" name="ossm">
                            </div>
                            <div class="col-md-11 p-l p-r">
                                <label for="MySQL">MySQL</label>
                            </div>
                        </div>
                        <div class="category">
                            <div class="col-md-1 p-l p-r">
                                <input type="checkbox" id="Wordpress" name="ossm">
                            </div>
                            <div class="col-md-11 p-l p-r">
                                <label for="Wordpress">Wordpress</label>
                            </div>
                        </div>
                    </div>

theratrove/Views/Search/For.cshtml
<div class="job_title">For</div>
<div class="borderfull-width"></div>
<div class="page-heading">
    <div class="category">
        <div class="col-md-1 p-l p-r">
            <input type="checkbox" id="PHP" name="ossm">
        </div>
        <div class="col-md-11 p-l p-r">
            <label for="PHP">PHP</label>
        </div>
    </div>
    <div class="category">
        <div class="col-md-1 p-l p-r">
            <input type="checkbox" id="HTML" name="ossm" checked="">
        </div>
        <div class="col-md-11 p-l p-r">
            <label for="HTML">HTML</label>
        </div>
    </div>
    <div class="category">
        <div class="col-md-1 p-l p-r">
            <input type="checkbox" id="CSS" name="ossm">
        </div>
        <div class="col-md-11 p-l p-r">
            <label for="CSS">CSS</label>
        </div>
    </div>
    <div class="category">
        <div class="col-md-1 p-l p-r">
            <input type="checkbox" id="JavaScript" name="ossm">
        </div>
        <div class="col-md-11 p-l p-r">
            <label for="JavaScript">JavaScript</label>
        </div>
    </div>
    <div class="category">
        <div class="col-md-1 p-l p-r">
            <input type="checkbox" id="jQueary" name="ossm">
        </div>
        <div class="col-md-11 p-l p-r">
            <label for="jQueary">jQueary</label>
        </div>
    </div>
    <div class="category">
        <div class="col-md-1 p-l p-r">
            <input type="checkbox" id="MySQL" name="ossm">
        </div>
        <div class="col-md-11 p-l p-r">
            <label for="MySQL">MySQL</label>
        </div>
    </div>
    <div class="category">
        <div class="col-md-1 p-l p-r">
            <input type="checkbox" id="Wordpress" name="ossm">
        </div>
        <div class="col-md-11 p-l p-r">
            <label for="Wordpress">Wordpress</label>
        </div>
    </div>
</div>

theratrove/Views/Search/GenderPreference.cshtml
<div class="job_title">Gender Preference</div>
<div class="borderfull-width"></div>
<button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown">No Preference <span class="caret"></span></button>

theratrove/Views/Search/Insurance.cshtml
<div class="job_title">Insurance</div>
<div class="borderfull-width"></div>
<div class="page-heading">
    <div class="category">
        <div class="col-md-1 p-l p-r">
            <input type="checkbox" id="cb_5" name="ossm">
        </div>
        <div class="col-md-11 p-l p-r">
            <label for="cb_5">$0 - $25 (231)</label>
        </div>
    </div>
    <div class="category">
        <div class="col-md-1 p-l p-r">
            <input type="checkbox" id="cb_4" name="ossm" checked="">
        </div>
        <div class="col-md-11 p-l p-r">
            <label for="cb_4">$25 - $50 (297)</label>
        </div>
    </div>
    <div class="category">
        <div class="col-md-1 p-l p-r">
            <input type="checkbox" id="cb_3" name="ossm">
        </div>
        <div class="col-md-11 p-l p-r">
            <label for="cb_3">$50 - $100 (78)</label>
        </div>
    </div>
    <div class="category">
        <div class="col-md-1 p-l p-r">
            <input type="checkbox" id="cb_2" name="ossm">
        </div>
        <div class="col-md-11 p-l p-r">
            <label for="cb_2">$100 - $200 (98)</label>
        </div>
    </div>
    <div class="category">
        <div class="col-md-1 p-l p-r">
            <input type="checkbox" id="cb_1" name="ossm">
        </div>
        <div class="col-md-11 p-l p-r">
            <label for="cb_1">$200+ (21)</label>
        </div>
    </div>
</div>

theratrove/Views/Search/Issues.cshtml
<div class="job_title">Issues</div>
<div class="borderfull-width"></div>
<div class="page-heading">
    <div class="category">
        <div class="col-md-1 p-l p-r">
            <input type="checkbox" id="cb_9" name="ossm">
        </div>
        <div class="col-md-11 p-l p-r">
            <label for="cb_9">All Type</label>
        </div>
    </div>
    <div class="category">
        <div class="col-md-1 p-l p-r">
            <input type="checkbox" id="cb_8" name="ossm" checked="">
        </div>
        <div class="col-md-11 p-l p-r">
            <label for="cb_8">Full Time</label>
        </div>
    </div>
    <div class="category">
        <div class="col-md-1 p-l p-r">
            <input type="checkbox" id="cb_7" name="ossm">
        </div>
        <div class="col-md-11 p-l p-r">
            <label for="cb_7">part Time</label>
        </div>
    </div>
    <div class="category">
        <div class="col-md-1 p-l p-r">
            <input type="checkbox" id="cb_6" name="ossm">
        </div>
        <div class="col-md-11 p-l p-r">
            <label for="cb_6">Freelancer</label>
        </div>
    </div>
</div>

theratrove/Views/Search/TherapistlistTest.cshtml
@*@model IEnumerable<theratrove.data.Therapist>*@

@model theratrove.Models.SearchResults

@{
    ViewBag.Title = "Therapist List";
}


<script type="text/javascript">
    var idList = [];
    var Faith = [];
    var For = [];
    var Issues = [];
    var Insurance = [];

    $(function () {
        // When a certain button is clicked, post your <form> data and URL to the Controller
        $("#btnSearch1").click(function () {
            $(this).parents('form').submit();
            //         $("input[name='checkboxes']:checked").each
            //(
            //  function () {
            //      //fill the array with the values
            //      alert(jQuery(this).val());

            //      var loopCounter = 0;
            //      idList.push([jQuery(this).data('type'), jQuery(this).val()]);
            //  }
            //);
            //         for (var i = 0; i < idList.length; i++) {
            //             //alert(idList[i][0]);
            //             if (idList[i][0] == 1) { //Faith
            //                 Faith.push(idList[i][1]);
            //             }
            //             else if (idList[i][0] == 2) { //For
            //                 //alert(idList[i][1]);
            //                 For.push(idList[i][1]);
            //             }
            //             else if (idList[i][0] == 3) { //Issues
            //                 //alert(idList[i][1]);
            //                 this.Issues.push(idList[i][1]);
            //             }
            //             else if (idList[i][0] == 4) {//Insurance
            //                 //alert(idList[i][1]);
            //                 this.Insurance.push(idList[i][1]);
            //             }
            //         }

            //         $.ajax({
            //             url: 'GetResults',
            //             type: 'POST',
            //             data: { checkboxTest: Faith }
            //         }).done(function (response) { //
            //             $("#server-results").html(response);
            //         });

            //         return false;
            //     });
        });


</script>
<div class="page_banner banner employer-banner">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <div class="banner-heading">Browse Matches</div>
            </div>
        </div>
    </div>
</div>
<main id="maincontent">
    <section class="resume">
        <div class="container">
            @using (Html.BeginForm("GetResult", "Search", FormMethod.Post))
            {
                <div class="row">
                    <div class="col-md-3">
                        @*@using (Ajax.BeginForm("FilterTherapist", "Search", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "divTheraistResult" }))
                            {*@

                        @*<form id="EmailRequestForm" method="post" action="Therapistlist">*@
                        <div class="job-search">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Job title / keywords">
                                <div class="search_icon"><span class="ti-briefcase"></span></div>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Zip Code">
                                <div class="search_icon"><span class="ti-location-pin"></span></div>
                            </div>
                            <a href="#" class="btn btn-default">Search Job Results</a>
                        </div>
                        @foreach (var x in Model.FilterOptions)
                        {
                            <div class="job_title">@x.FilterName</div>
                            <div class="borderfull-width"></div>
                            <div class="page-heading">
                                <div class="category">
                                    @switch ((theratrove.Models.ControlTypeEnum)x.FilterControlType)
                                    {
                                        case theratrove.Models.ControlTypeEnum.CheckBox:
                                            foreach (var item in x.FilterValues)
                                            {
                                                <div class="col-md-1 p-l p-r">
                                                    <input type="checkbox" id="@item.Value" name="@string.Format("ctrl_{0}",@x.FilteType)" value="@item.Value" data-type="@x.FilteType">
                                                </div>
                                                <div class="col-md-11 p-l p-r">
                                                    <label>@item.Key</label>
                                                </div>
                                            }
                                            break;
                                        case theratrove.Models.ControlTypeEnum.DropDown:
                                            <div class="col-md-1 p-l p-r">
                                                <select name="@string.Format("ctrl_{0}",@x.FilteType)" data-type="@x.FilteType">
                                                    @foreach (var item in x.FilterValues)
                                                    {
                                                        <option value="@item.Value">@item.Key</option>
                                                    }
                                                </select>
                                            </div>
                                            break;
                                    }
                                </div>
                            </div>
                        }
                        <div class="job_title">Gender Preference</div>
                        <div class="borderfull-width"></div>
                        @*<button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown" id="btnSearch1">No Preference <span class="caret"></span></button>*@
                        <input type="submit" value="OK" name="btnSearch1" />

                        @*</form>*@
                    </div>
                    <div class="col-md-9">
                        <div id="divTheraistResult">
                            @Html.Partial("_TherapistList", Model)
                        </div>
                    </div>
                </div>
            }
        </div>
    </section>
</main>

theratrove/Views/Search/_TherapistList.cshtml
@model theratrove.Models.SearchResults

<div class="col-md-7 col-sm-7 p-l">
    <div class="page-heading">
        @if (Model.NoOfRecords < 0)
        {
            <p>No Result Found</p>
        }
        else
        {
            <p> @Model.RecordsRange </p>
        }
    </div>
</div>
<div class="col-md-5 col-sm-5 filter p-r text-right">

    <div class="col-md-7 col-sm-5"><p>Short by:</p></div>
    <div class="col-md-5 col-sm-7 p-r">
        <div class="dropdown">
            <button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown">By Default <span class="caret"></span></button>
            <ul class="dropdown-menu pull-right">
                <li><a href="#">Executive</a></li>
                <li><a href="#">SEO</a></li>
                <li><a href="#">Java Developer</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="clearfix"></div>
@if (Model != null && Model.TherapistList.Count() > 0)
{
    <div class="page_listing candidate">
        @foreach (var item in Model.TherapistList)
        {
            <div class="sorting_content">
                @*//To do: need to get Image of therapist*@
                <div class="tab-image">
                    <img src="/assets/images/candidates/candidate-1.png" alt="" class="img-responsive">
                </div>

                <div class="overflow">
                    <div class="text-shorting">
                        <h1>
                            @Html.ActionLink(string.Format("{0} {1}", item.FirstName, item.LastName), "Therapist", "Search", new { Id = item.Id }, null)
                        </h1>
                        <ul class="unstyled">
                            <li>@item.Title</li>
                            <li><span><strong>Rate : </strong> <i class="fa fa-money"></i> @item.AvgCost</span></li>
                        </ul>
                        <p></p>
                    </div>
                    <div class="bottom_text">
                        <div class="contact_details col-md-4 col-sm-4 p-l">
                            <span><strong>Location:</strong> @item.Location</span>
                        </div>
                        <div class="contact_details col-md-8 col-sm-8 p-l">
                            <span>
                                <strong>Skills:</strong>
                                @if (item.TherapistTypesOfTherapies != null && item.TherapistTypesOfTherapies.Count > 0)
                                {
                                    string.Join(",", item.TherapistTypesOfTherapies.Select(f => f.TherapyType.Name));
                                }
                            </span>
                        </div>
                        <p></p>
                        <p class="col-md-12 p-l">
                            @item.AboutMe
                        </p>
                    </div>
                </div>
            </div>
        }
    </div>
    @*<ul class="pagination pull-right">
        @if (Model.NoOfRecords > 0)
        {
            <li class="active"><a href="#"><i class="fa fa-angle-left"></i></a></li>
            for (var i = 1; i <= Model.NoOfRecords / 1; i++)
            {
                <li><a href="#" name="pageNumber" id="pageNumber">@i </a></li>
                                        @Html.HiddenFor(d => d.CurrentPage);
            }
            <li class="active"><a href="#"><i class="fa fa-angle-right"></i></a></li>
        }
    </ul>*@
}
else
{
    <p> No record found  </p>
}